name: CI

on:
  push:
    branches:
      - gen-branch
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 18.x
    - run: npm i && npm run lint